# see https://github.com/golangci/golangci-lint for all possible config options.

linters-settings:
  maligned:
    suggest-new: true
  lll:
    line-length: 125
    tab-width: 2

linters:
  enable-all: true
  disable:
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - gomnd
    - nlreturn
    - prealloc

max-same-issues: 0
